/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.casualIntellect;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.casualintellect.casualIntellect.NestedExpression#getChild <em>Child</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getNestedExpression()
 * @model
 * @generated
 */
public interface NestedExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Child</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Child</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child</em>' containment reference.
   * @see #setChild(Expression)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getNestedExpression_Child()
   * @model containment="true"
   * @generated
   */
  Expression getChild();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.NestedExpression#getChild <em>Child</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Child</em>' containment reference.
   * @see #getChild()
   * @generated
   */
  void setChild(Expression value);

} // NestedExpression
